---
- hosts: gyzszaboW{{BIG_number}}
  gather_facts: no
  tasks:
    - name: Powershell | Check for ServerManager Powershell module
      win_psmodule:
        name: ServerManager
        state: present

    - name: Windows | Install .NET Framework Core
      win_feature:
        name: NET-Framework-Core
        state: present

    - name: Windows | Install .NET Framework 3.5
      win_feature:
        name: NET-Framework-Features
        state: present

    - name: Windows | Install .NET Framework 4.5 Features
      win_feature:
        name: NET-Framework-45-Features
        state: present
        include_sub_features: True

    - name: Windows | Install Windows Process Activation Service
      win_feature:
        name: WAS
        state: present
        include_sub_features: True
