---
- name: Guest Creation
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: all
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      vmware_guest:
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        validate_certs: no
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        networks:
          - name: "{{ network }}"
            ip: "{{ net_ip }}"
            netmask: "{{ net_mask }}"
            gateway: "{{ net_gw }}"
        cluster: "{{ cluster }}"
        customization:
          dns_servers: "{{ dns_server }}"
        wait_for_ip_address: yes
      register: vm_result
