---
- name: Guest Creation

  gather_facts: no

  vars_files:
    - ultimate_vars.yml

  hosts: localhost

  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      vmware_guest:
        name: "{{ vm_name }}{{BIG_number}}"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        validate_certs: no
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        networks:
          - name: "{{ network }}"
            ip: "{{ net_ip }}{{BIG_number}}"
            netmask: "{{ net_mask }}"
            gateway: "{{ net_gw }}"
        cluster: "{{ cluster }}"
        customization:
          dns_servers: "{{ dns_server }}"
          domain: "{{ domain }}"
          hostname: "{{ vm_name }}"
          autologon: yes
          fullname: "{{ win20x_local_admin }}"
          password: "{{ win20x_local_passw }}"
          domainadmin: "{{ osseng_domain_adminname }}"
          domainadminpassword: "{{ osseng_domain_adminpassw }}"
          joindomain: "{{ joindomain }}"
        wait_for_customization: yes
        wait_for_ip_address: yes
      register: vm_result

  handlers:
    - name: Reboot Windows server
      win_reboot:

